version: '3.8'

networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/regru/ssl/:/etc/regru/ssl'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend_api
    environment:
      - ENV=production
    networks:
      - dev
    expose:
      - "8000"  # Важно для связи между контейнерами

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    expose:
      - "3000"  # React по умолчанию на 3000 порту